# syntax = docker/dockerfile:1.3
FROM maven:3-jdk-8
WORKDIR /usr/src/app
COPY . .
RUN java -version &\
    mvn -version
ARG SONAR_HOST
ARG SONAR_LOGIN
ARG CI_PROJECT_NAME
ARG CI_COMMIT_REF_NAME
ARG CI_PROJECT_TITLE
ARG CI_PROJECT_URL
RUN --mount=type=cache,target=/.m2/repository \
    mvn clean verify -U -Dmaven.repo.local=/.m2/repository -s ./.m2/settings.xml -Dfile.encoding=UTF-8 \
    sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.java.binaries=target/classes -Dsonar.java.test.binaries=target/test-classes \
    -Dsonar.host.url=${SONAR_HOST} -Dsonar.login=${SONAR_LOGIN} -Dsonar.projectKey=${CI_PROJECT_NAME} -Dsonar.projectName=${CI_PROJECT_NAME} -Dsonar.branch.name=${CI_COMMIT_REF_NAME} -Dsonar.projectVersion=${CI_COMMIT_REF_NAME} -Dsonar.projectDescription=${CI_PROJECT_TITLE} -Dsonar.links.homepage=${CI_PROJECT_URL}
