{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "project.serviceAccountName" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-service-rbac
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - patch
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "project.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "project.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: k8s-service-rbac
  apiGroup: rbac.authorization.k8s.io
{{- end }}
